### ISSUE TITLE
Can't build vignette with latest version of spatstat packages

### ISSUE THREAD

**Issue by nicocriscuolo** [joenomiddlename/PStestR#1]
Hi and thanks for this great package!

I was reinstalling it after updating most of my packages, and I encountered an error when building the vignette. The problem was related to the function "rmh" which apparently is not the same you used in the .Rmd file in the latest versions of the spatstat packages (core, geom, ecc.)

I downgraded to previous version and I was able to install PStestR and build the vignette.

Cheers!

**Comment by joenomiddlename** [comment]
Thanks for sharing this and great to hear that you're enjoying the package!

I will attempt to fix this ASAP.

Joe

**Comment by joenomiddlename** [comment]
Thanks so much for the thorough information regarding the error! 

The problem was due to the migration of the function rmh() to the new package "spatstat.random". The issue should now be fixed (The R CMD Check passed and the changes have been pushed).

Please let me know when you are able to successfully build the package and I will close the issue.

Thanks again, and feel free to message me with any questions.
Joe

**Comment by nicocriscuolo** [comment]
Tested on another computer after updating all the spatstat libraries and everything worked correctly.

Thank you very much for your availability!

Nico

**Comment by joenomiddlename** [comment]
Thanks for letting me know!
